### ISSUE TITLE
registration and create user

### ISSUE THREAD

**Issue by pchauhan77** [danielfsousa/express-rest-boilerplate#291]
what is the need for registration and before creating the user. what is the use of this thing? can we create a user direct?
Please elaborate on this.

**Comment by tehstormcrow** [comment]
Greetings,

register path is used by users of our website to register an account, it omits role from req.body, so a user cannot just register as an admin, it also returns accessToken as response

createUser is used by admin to create a user, since it doesn't omit role from req.body, it is possible to create an admin. it doesn't return token, since it is not a path used for authentication but for system administration.

Hope this helps you
